# Generated by Django 4.1.2 on 2022-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('address', models.TextField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('branches', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('materialsprovided', models.CharField(max_length=100)),
            ],
        ),
    ]
