# Generated by Django 4.1.2 on 2022-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_form_email_alter_form_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='branches',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='materialsprovided',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
